on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd site/client && npm build
      - name: Initialize Backend
        run: cd site/server && npm start
      - name: Initialize Frontend
        run: cd site/client && npm start

      - name: Test
        run: ls -la
