on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: cd site/client && npm install
      - name: NODE_OPTIONS='--openssl-legacy-provider' npm run build
        run: nvm use 16 && cd site/client && npm run build
      - name: Start Backend
        run: cd site/server && npm start
      - name: Start Frontend
        run: cd site/client && npm start

      - name: Test
        run: ls -la
