on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Build
        run: |
          cd site/client
          npm install
          npm run build
          cd ../server
          npm install
      - name: Start Backend
        run: cd site/server && npm start &
      - name: Start Frontend
        run: cd site/client && npm start &

      - name: Test
        run: ls -la
      - name: Check Processes
        run: ps
